# Generated by Django 6.0.2 on 2026-02-10 23:59

import django.db.models.deletion
import django.utils.timezone
import requetes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('adresse', models.TextField()),
                ('secteur_activite', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='CommunicationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('visibilite', models.CharField(choices=[('global', 'Global'), ('company', 'Entreprise'), ('pole', 'Pôle')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communications', to=settings.AUTH_USER_MODEL)),
                ('entreprise_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='requetes.entreprise')),
            ],
            options={
                'verbose_name': 'Communication',
                'verbose_name_plural': 'Communications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationPieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=requetes.models.piece_jointe_upload_to)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces_jointes_communications', to=settings.AUTH_USER_MODEL)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='requetes.communicationpost')),
            ],
            options={
                'verbose_name': 'Pièce jointe communication',
                'verbose_name_plural': 'Pièces jointes communication',
            },
        ),
        migrations.CreateModel(
            name='DelegueSyndical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandats_delegue', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegues', to='requetes.entreprise')),
            ],
            options={
                'verbose_name': 'Délégué syndical',
                'verbose_name_plural': 'Délégués syndicaux',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION_STATUT', 'Modification statut'), ('AJOUT_COMMENTAIRE', 'Ajout commentaire'), ('ASSIGNATION', 'Assignation'), ('REUNION_PLANIFIEE', 'Réunion planifiée'), ('PIECE_JOINTE_AJOUTEE', 'Pièce jointe ajoutée'), ('TRANSMISSION', 'Transmission'), ('CLOTURE', 'Clôture')], max_length=40)),
                ('champ_modifie', models.CharField(blank=True, max_length=120, null=True)),
                ('ancienne_valeur', models.TextField(blank=True, null=True)),
                ('nouvelle_valeur', models.TextField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'action",
                'verbose_name_plural': 'Historique des actions',
            },
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('types_problemes', models.JSONField(blank=True, default=list)),
                ('chef_de_pole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poles_diriges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pôle',
                'verbose_name_plural': 'Pôles',
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(editable=False, max_length=20, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_INSTRUCTION', 'En instruction'), ('ATTENTE_REUNION', 'Attente réunion'), ('TRANSMIS_BUREAU', 'Transmis au bureau'), ('CLOTURE', 'Clôturé'), ('ARCHIVE', 'Archivé')], default='OUVERT', max_length=30)),
                ('date_ouverture', models.DateField(default=django.utils.timezone.now)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('synthese', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_responsables', to=settings.AUTH_USER_MODEL)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='requetes.pole')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-created_at'],
                'permissions': [('peut_valider_dossier', 'Peut valider un dossier')],
            },
        ),
        migrations.CreateModel(
            name='DocumentSyndical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('annee', models.PositiveIntegerField()),
                ('categorie', models.CharField(max_length=120)),
                ('fichier', models.FileField(upload_to=requetes.models.piece_jointe_upload_to)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_televerses', to=settings.AUTH_USER_MODEL)),
                ('pole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='requetes.pole')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='communicationpost',
            name='pole_cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='requetes.pole'),
        ),
        migrations.CreateModel(
            name='PoleMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('head', 'Responsable'), ('assistant', 'Adjoint'), ('member', 'Membre')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_detail', to='requetes.pole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_poles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre de pôle',
                'verbose_name_plural': 'Membres de pôle',
            },
        ),
        migrations.AddField(
            model_name='pole',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='poles', through='requetes.PoleMembre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('pole_manager', 'Chef de pôle'), ('delegate', 'Délégué'), ('member', 'Membre')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils', to='requetes.entreprise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(choices=[('working_conditions_remuneration', 'Conditions de travail et rémunération'), ('training_career', 'Formation et carrière'), ('social_mediation', 'Dialogue social et médiation'), ('health_safety_wellbeing', 'Santé et sécurité'), ('legal_compliance', 'Juridique et conformité'), ('communication_awareness', 'Communication'), ('innovation_digital_transformation', 'Innovation et transformation digitale'), ('external_relations_partnerships', 'Relations extérieures et partenariats'), ('youth_new_employees', 'Jeunesse et nouveaux employés'), ('sport_wellbeing', 'Sport et bien-être'), ('other', 'Autre')], max_length=40)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('new', 'Nouveau'), ('info_needed', "Besoin d'infos"), ('processing', 'En traitement'), ('hr_escalated', 'Escaladé RH'), ('hr_pending', 'En attente RH'), ('resolved', 'Résolu'), ('closed', 'Clôturé')], default='new', max_length=30)),
                ('priorite', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('delegue_syndical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requetes_deleguees', to='requetes.deleguesyndical')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requetes_principales', to='requetes.dossier')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requetes', to='requetes.entreprise')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requetes', to='requetes.pole')),
                ('travailleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requetes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requête',
                'verbose_name_plural': 'Requêtes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=requetes.models.piece_jointe_upload_to)),
                ('type_document', models.CharField(choices=[('CONTRAT', 'Contrat'), ('ATTESTATION', 'Attestation'), ('COURRIER', 'Courrier'), ('PHOTO', 'Photo'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces_jointes', to=settings.AUTH_USER_MODEL)),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='requetes.requete')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('ticket_update', 'Mise à jour requête'), ('new_message', 'Nouveau message'), ('info_request', "Demande d'information"), ('general', 'Générale')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('requete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='requetes.requete')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractionRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_nom', models.CharField(max_length=120)),
                ('contact_role', models.CharField(max_length=120)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions_rh', to=settings.AUTH_USER_MODEL)),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_rh', to='requetes.requete')),
            ],
            options={
                'verbose_name': 'Interaction RH',
                'verbose_name_plural': 'Interactions RH',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dossier',
            name='requetes',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='requetes.requete'),
        ),
        migrations.CreateModel(
            name='RequeteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('is_interne', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='requetes.requete')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_requetes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message de requête',
                'verbose_name_plural': 'Messages de requête',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reunion', models.CharField(choices=[('TELEPHONIQUE', 'Téléphonique'), ('PRESENTIEL', 'Présentiel'), ('VISIOCONFERENCE', 'Visioconférence')], max_length=20)),
                ('date_heure', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('ordre_du_jour', models.TextField()),
                ('compte_rendu', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reunions_creees', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions', to='requetes.dossier')),
                ('participants', models.ManyToManyField(blank=True, related_name='reunions_participees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réunion',
                'verbose_name_plural': 'Réunions',
            },
        ),
        migrations.CreateModel(
            name='TemplateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_template', models.CharField(choices=[('convocation', 'Convocation'), ('pv', 'Procès-verbal'), ('compte_rendu', 'Compte rendu'), ('lettre', 'Lettre')], max_length=20)),
                ('contenu', models.TextField()),
                ('is_global', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='requetes.pole')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deleguesyndical',
            index=models.Index(fields=['entreprise', 'is_active'], name='requetes_de_entrepr_9a42b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='deleguesyndical',
            constraint=models.UniqueConstraint(fields=('user', 'entreprise'), name='unique_delegue_par_entreprise'),
        ),
        migrations.AddIndex(
            model_name='historiqueaction',
            index=models.Index(fields=['content_type', 'object_id'], name='requetes_hi_content_f58d52_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueaction',
            index=models.Index(fields=['timestamp'], name='requetes_hi_timesta_a969c1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsyndical',
            index=models.Index(fields=['annee', 'categorie'], name='requetes_do_annee_c2727a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsyndical',
            index=models.Index(fields=['pole'], name='requetes_do_pole_id_2a84ea_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationpost',
            index=models.Index(fields=['visibilite', 'created_at'], name='requetes_co_visibil_f6d311_idx'),
        ),
        migrations.AddConstraint(
            model_name='polemembre',
            constraint=models.UniqueConstraint(fields=('pole', 'user'), name='unique_pole_membre'),
        ),
        migrations.AddConstraint(
            model_name='pole',
            constraint=models.CheckConstraint(condition=models.Q(('chef_de_pole__isnull', False)), name='pole_chef_de_pole_not_null'),
        ),
        migrations.AddIndex(
            model_name='profilutilisateur',
            index=models.Index(fields=['role', 'entreprise'], name='requetes_pr_role_478ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='requete',
            index=models.Index(fields=['statut', 'pole', 'created_at'], name='requetes_re_statut_f462c3_idx'),
        ),
        migrations.AddIndex(
            model_name='requete',
            index=models.Index(fields=['travailleur', 'statut'], name='requetes_re_travail_d8c02b_idx'),
        ),
        migrations.AddConstraint(
            model_name='requete',
            constraint=models.UniqueConstraint(fields=('numero_reference',), name='unique_numero_reference'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['utilisateur', 'is_read'], name='requetes_no_utilisa_5a5e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='requetes_no_created_a0af19_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionrh',
            index=models.Index(fields=['requete', 'created_at'], name='requetes_in_requete_a192af_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['pole', 'statut'], name='requetes_do_pole_id_771f43_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['numero_dossier'], name='requetes_do_numero__27d9a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='dossier',
            constraint=models.UniqueConstraint(fields=('numero_dossier',), name='unique_numero_dossier'),
        ),
        migrations.AddIndex(
            model_name='requetemessage',
            index=models.Index(fields=['requete', 'created_at'], name='requetes_re_requete_8695dd_idx'),
        ),
        migrations.AddIndex(
            model_name='templatedocument',
            index=models.Index(fields=['is_global', 'is_active'], name='requetes_te_is_glob_d45275_idx'),
        ),
        migrations.AddIndex(
            model_name='templatedocument',
            index=models.Index(fields=['pole'], name='requetes_te_pole_id_240e5f_idx'),
        ),
    ]
