# Generated by Django 6.0.2 on 2026-02-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requetes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='photo',
            field=models.ImageField(default='profils/default.png', upload_to='profils/%Y/%m/'),
        ),
    ]
