# Generated by Django 6.0.2 on 2026-02-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requetes', '0002_profilutilisateur_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='adresse_residence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='ancien_syndicat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='consentement_donnees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='contrat_travail',
            field=models.FileField(blank=True, null=True, upload_to='contrats/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='date_adhesion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='departement',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='dernier_bulletin_salaire',
            field=models.FileField(blank=True, null=True, upload_to='bulletins/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='engagement_statuts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='lieu_travail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='matricule_interne',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='motivation_adhesion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='nom_ancien_syndicat',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='numero_piece_identite',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='photo_identite',
            field=models.ImageField(blank=True, null=True, upload_to='photos_identite/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='pieces_identite/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='poste',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='premiere_adhesion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='sexe',
            field=models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Féminin'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('journalier', 'Journalier'), ('interim', 'Intérim'), ('autre', 'Autre')], max_length=20),
        ),
    ]
