# Generated by Django 6.0.2 on 2026-02-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requetes', '0006_seed_entreprises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('pole_manager', 'Chef de pôle'), ('head', 'Chef de pôle (membre)'), ('assistant', 'Assistant de pôle'), ('delegate', 'Délégué'), ('member', 'Membre')], max_length=20),
        ),
    ]
