# Generated by Django 6.0.2 on 2026-02-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requetes', '0012_poleworkflow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='poleworkflow',
            new_name='requetes_po_pole_id_5f6e2a_idx',
            old_name='poleworkflow_pole_from_active_idx',
        ),
    ]
