# Generated by Django 6.0.2 on 2026-02-20 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requetes', '0015_maquette_compte_rendu_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteRequete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('call', 'Appel téléphonique'), ('meeting', 'Rendez-vous'), ('document', 'Document à fournir'), ('note', 'Note interne')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_planifiee', models.DateTimeField()),
                ('statut', models.CharField(choices=[('planned', 'Planifié'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='planned', max_length=20)),
                ('date_realisation', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites_requetes_creees', to=settings.AUTH_USER_MODEL)),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='requetes.requete')),
            ],
            options={
                'verbose_name': 'Activité requête',
                'verbose_name_plural': 'Activités requête',
                'ordering': ['-date_planifiee'],
                'indexes': [models.Index(fields=['requete', 'date_planifiee'], name='requetes_ac_requete_cfcdae_idx')],
            },
        ),
    ]
