# Generated by Django 6.0.2 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requetes", "0016_add_activite_requete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activiterequete",
            name="type_activite",
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="activiterequete",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
