# Generated by Django 6.0.2 on 2026-02-24

from django.db import migrations, models
import requetes.models


class Migration(migrations.Migration):

    dependencies = [
        ("requetes", "0017_activite_requete_extra_data_and_type_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="activiterequete",
            name="piece_jointe_compte_rendu",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=requetes.models.activite_compte_rendu_upload_to,
                verbose_name="Pièce jointe compte rendu",
            ),
        ),
    ]
