# Generated by Django 6.0.2 on 2026-02-27 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requetes', '0022_notationentreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.SlugField(help_text='Identifiant unique (ex: evaluation_grille, suivi_primes).', max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Désactiver au lieu de supprimer pour préserver l'historique.")),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Modèle d'activité",
                'verbose_name_plural': "Modèles d'activité",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='activiterequete',
            name='activite_template',
            field=models.ForeignKey(blank=True, help_text='Si renseigné, type_activite et champs personnalisés viennent de ce modèle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activites_requetes', to='requetes.activitetemplate'),
        ),
        migrations.CreateModel(
            name='ActiviteTemplatePole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('activite_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_poles', to='requetes.activitetemplate')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_activites', to='requetes.pole')),
            ],
            options={
                'verbose_name': 'Affectation activité → pôle',
                'verbose_name_plural': 'Affectations activité → pôle',
                'ordering': ['pole', 'ordre', 'activite_template'],
            },
        ),
        migrations.AddField(
            model_name='activitetemplate',
            name='poles',
            field=models.ManyToManyField(blank=True, help_text='Pôles pour lesquels cette activité est disponible dans le workflow.', related_name='activite_templates', through='requetes.ActiviteTemplatePole', to='requetes.pole'),
        ),
        migrations.CreateModel(
            name='ChampActiviteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.SlugField(help_text='Clé du champ (ex: date_limite, type_prime).', max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('type_champ', models.CharField(choices=[('text', 'Texte'), ('textarea', 'Zone de texte'), ('number', 'Nombre'), ('date', 'Date'), ('datetime', 'Date et heure'), ('boolean', 'Oui/Non'), ('file', 'Fichier'), ('choice', 'Liste de choix')], db_index=True, max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list, help_text='Pour type=choice : liste de valeurs [{"value": "x", "label": "Libellé"}].')),
                ('is_active', models.BooleanField(default=True, help_text="Désactiver un champ sans le supprimer pour ne pas casser l'historique.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activite_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs', to='requetes.activitetemplate')),
            ],
            options={
                'verbose_name': "Champ de modèle d'activité",
                'verbose_name_plural': "Champs de modèles d'activité",
                'ordering': ['activite_template', 'ordre', 'nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='activitetemplatepole',
            constraint=models.UniqueConstraint(fields=('activite_template', 'pole'), name='unique_activite_template_pole'),
        ),
        migrations.AddConstraint(
            model_name='champactivitetemplate',
            constraint=models.UniqueConstraint(fields=('activite_template', 'nom'), name='unique_activite_template_champ_nom'),
        ),
    ]
