# Generated by Django 6.0.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("requetes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("fichier", models.FileField(upload_to=documents.models.document_fichier_upload_to)),
                ("confidentialite", models.CharField(
                    choices=[
                        ("PUBLIC", "Public"),
                        ("POLE", "Pôle"),
                        ("BUREAU", "Bureau"),
                        ("CONFIDENTIEL", "Confidentiel"),
                    ],
                    db_index=True,
                    default="POLE",
                    max_length=20,
                )),
                ("statut", models.CharField(
                    choices=[
                        ("ACTIF", "Actif"),
                        ("TRANSFERE", "Transféré"),
                        ("CLOTURE", "Clôturé"),
                        ("ARCHIVE", "Archivé"),
                    ],
                    db_index=True,
                    default="ACTIF",
                    max_length=20,
                )),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="documents_crees",
                    to=settings.AUTH_USER_MODEL,
                )),
                ("pole", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="documents_gestion",
                    to="requetes.pole",
                )),
                ("requete", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="documents_lies",
                    to="requetes.requete",
                )),
            ],
            options={
                "verbose_name": "Document (gestion)",
                "verbose_name_plural": "Documents (gestion)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentHistorique",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(
                    choices=[
                        ("CREATION", "Création"),
                        ("MODIFICATION", "Modification"),
                        ("TRANSFERT", "Transfert"),
                        ("ARCHIVAGE", "Archivage"),
                    ],
                    db_index=True,
                    max_length=20,
                )),
                ("champ_modifie", models.CharField(blank=True, max_length=120, null=True)),
                ("ancienne_valeur", models.TextField(blank=True, null=True)),
                ("nouvelle_valeur", models.TextField(blank=True, null=True)),
                ("commentaire", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("document", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="historique",
                    to="documents.document",
                )),
                ("utilisateur", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="actions_documents",
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                "verbose_name": "Historique document",
                "verbose_name_plural": "Historiques documents",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["pole", "statut"], name="documents_doc_pole_s_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["confidentialite", "statut"], name="documents_doc_conf_s_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["requete"], name="documents_doc_requet_idx"),
        ),
        migrations.AddIndex(
            model_name="documenthistorique",
            index=models.Index(fields=["document", "timestamp"], name="documents_doc_doc_ts_idx"),
        ),
    ]
