# Generated by Django 6.0.2

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_suivi_requete",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True si ce document est le suivi automatique d'une requête (un seul par requête).",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="fichier",
            field=models.FileField(
                blank=True,
                help_text="Optionnel pour les documents de suivi requête (générés automatiquement).",
                null=True,
                upload_to=documents.models.document_fichier_upload_to,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["is_suivi_requete"], name="documents_do_is_suiv_idx"),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_suivi_requete=True),
                fields=("requete",),
                name="documents_unique_suivi_per_requete",
            ),
        ),
    ]
