# Generated by Django 6.0.2 on 2026-02-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_created_by_db_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_pole_id_f7acfe_idx',
            old_name='documents_doc_pole_s_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_confide_3c5ae6_idx',
            old_name='documents_doc_conf_s_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_requete_94bf51_idx',
            old_name='documents_doc_requet_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_is_suiv_104091_idx',
            old_name='documents_do_is_suiv_idx',
        ),
        migrations.RenameIndex(
            model_name='documenthistorique',
            new_name='documents_d_documen_d343d8_idx',
            old_name='documents_doc_doc_ts_idx',
        ),
    ]
